version: "3.8"

services:
  postgres:
    image: postgres:18-alpine
    container_name: fullstack-postgres
    environment:
      POSTGRES_DB: bookstore
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
